### ISSUE TITLE
Problem with mapping of event attribute to async event handler in aggregate and error message id duplication

### ISSUE THREAD

**Issue by lifinsky** [ecotoneframework/ecotone-dev#306]
**Ecotone version(s) affected**: 1.215.1

**Description**  
Have you forgot to add use #[TargetIdentifier] in your Command or `aggregate.id` in metadata or provide #[Identifier] to MessageGateway

**How to reproduce**  
```
final readonly class IssueWasReported
{
    public function __construct(#[TargetIdentifier('id')] public int $issueId) {}
}
```

```
#[Delayed(100)]
#[Asynchronous(EcotoneConfiguration::NOTIFICATIONS_CHANNEL)]
#[EventHandler(endpointId: 'OnIssueReported')]
public function onEvent(IssueWasReported $event): void
{
}
```

But without TargetIdentifier I will recieve error
`Annotation Ecotone\Modelling\Attribute\TargetAggregateIdentifier was not found for property publicissueIdint`

And also this case additionally add duplication error in ecotone_error_messages, because already has exception on other async endpoint for notifications queue:
```
    #[Asynchronous(EcotoneConfiguration::NOTIFICATIONS_CHANNEL)]
    #[EventHandler(endpointId: "confirmReceivedIssueNotification")]
    public function sendNotificationToConfirmReceivedIssue(IssueWasReported $event, #[Header("ecotone.dlq.message_replied")] ?string $wasReplied): void
    {
        $issue = Issue::find($event->issueId);

// This is just for demo purposes. The first time email is sent, it will fail and will be delivered to DLQ
// after replaying it from Ecotone Pulse, it will be handled correctly.
        if (is_null($wasReplied)) {
            throw new \InvalidArgumentException("Can't render template, missing issue id parameter");
        }

        \Mail::to($issue->email)->send(new ConfirmReportedIssueMail($event->issueId));
    }
```

**Possible Solution**  
Generate unique message_id for every async endpoint or add additional column "endpoint_id" to ecotone_error_messages. Add clear description in documentation how to map event attribute to aggregate id.
This is not working: https://docs.ecotone.tech/modelling/command-handling/saga#targeting-identifier-from-event-command

**Context**  
```
  "exception-message": "Aggregate App\\Models\\Issue for calling onEvent was not as no identifiers were provided. Have you forgot to add use #[TargetIdentifier] in your Command or `aggregate.id` in metadata or provide #[Identifier] to MessageGateway?",
  "exception-stacktrace": "#0 /data/app/vendor/ecotone/ecotone/src/Modelling/AggregateFlow/LoadAggregate/LoadStateBasedAggregateService.php(66):
```

**Comment by lifinsky** [comment]
Maybe we should improve ClassPropertyDefinition::__toString() method also?
`$visibility property $type $attribute of $class class`
For example:
public property int issueId of IssueWasReported class

**Comment by dgafka** [comment]
> But with TargetIdentifier I will recieve error
Annotation Ecotone\Modelling\Attribute\TargetAggregateIdentifier was not found for property publicissueIdint

Hmm that should work. Possibily latest rewrite of storing and load Aggregate had to change it (https://github.com/ecotoneframework/ecotone-dev/pull/205). @unixslayer are you able to take a look on this?

> Generate unique message_id for every async endpoint or add additional column "endpoint_id" to ecotone_error_messages. Add clear description in documentation how to map event attribute to aggregate id.

This is by design. Event is always same Message no matter how many subscribers it has. Therefore regenerating message id per Subscriber would actually confuse history. Ecotone solves that differently. 
Each Asynchronous Event Handler get it's own copy of the Message, yet with own [routing slip](https://www.enterpriseintegrationpatterns.com/patterns/messaging/RoutingTable.html). 

Deduplication of Messages is based on the Message Id + Routing slip, which makes it unique. 
Therefore we may have two Error Messages with same Message Id in Dead Letter, as each relates to different Event Handler. 
If you take in Message Headers however, you will see the `routingSlip` header is different tho.

Let me know if above is clear :)

**Comment by unixslayer** [comment]
Yes. I'll take a look.

**Comment by lifinsky** [comment]
But we receive duplication error when in error messages table for dead letter when have more than 1 async endpoint with exception (in example above - event handler in aggregate goes in an infinite loop and cannot insert message in dead letter queue)

**Comment by lifinsky** [comment]
It would be logical to have a message in the dead letter table for each handler independently. Case with more than 1 async endpoint for the same event is popular.

**Comment by lifinsky** [comment]
Maybe we should use different primary key column for dbal dead letter table?
https://github.com/ecotoneframework/dbal/blob/66277082b4bf5cd0fe6f964fbb4efe80ee4322fd/src/Recoverability/DbalDeadLetterHandler.php#L231

**Comment by dgafka** [comment]
> Maybe we should use different primary key column for dbal dead letter table?
https://github.com/ecotoneframework/dbal/blob/66277082b4bf5cd0fe6f964fbb4efe80ee4322fd/src/Recoverability/DbalDeadLetterHandler.php#L231

Hmmm true, this should be changed. Most likely `message_id` + `routing_slip` and `endpoint_id`

**Comment by dgafka** [comment]
@lifinsky I will take a look on setting up correct primary keys for that.
However you will most likely need to do migration if you've the table on production already, as I would like to avoid bumping Ecotone major version due to that :)

**Comment by lifinsky** [comment]
@dgafka For new table you can add new columns (not nullable) and composite primary key, for existing projects (table already exists) we can use default dbal dead letter configuration, new projects or after migration need to change dbal configuration (for example via DbalConfiguration withDeadLetterNewStorage method)  - and in Ecotone V2 use default new table and remove method in DbalConfiguration builder

**Comment by lifinsky** [comment]
We are ready for new DbalConfiguration method or using ecotone configuration for Symfony/Laravel before new major version fix this issue, and add migration for existing table or after processing of dead letter messages replace table with new schema

**Comment by lifinsky** [comment]
Problem with error message id duplication was solved in https://github.com/ecotoneframework/ecotone-dev/pull/308

**Comment by dgafka** [comment]
Fixed with 1.218.0 - https://github.com/ecotoneframework/ecotone-dev/releases/tag/1.218.0
Also updated docs on Identifier Mapping - https://docs.ecotone.tech/modelling/command-handling/identifier-mapping

**Comment by lifinsky** [comment]
Thank you!

**Comment by unixslayer** [comment]
@lifinsky is identifier mapping still an issue? I got sick for over a week so couldn't take a look at the problem.

**Comment by dgafka** [comment]
@unixslayer it should be all good now :)
